### ISSUE TITLE
Very bad performance when run inside pod

### ISSUE THREAD

**Issue by xdexter** [awslabs/aws-codebuild-jenkins-plugin#64] opened 2018-06-18 22:05 UTC
Hello!

I'm using the AWSCodeBuild plugin in a Kubernetes Cluster with Kubernetes plugin (https://github.com/jenkinsci/kubernetes-plugin), when i allocate a pod to run my pipeline/awscodebuild command the perfomance in zip action is very bad, normally my zip takes ~10seconds to complete but in this case the same action takes ~6minutes.

If i connect to a container and run the zip command manually the performance is normally, the "problem" only happen inside plugin.

My Jenkinsfile: https://pastebin.com/yCGMeA2R

There are could help me please?

Regards

**Comment by xdexter** [comment] 2018-06-20 16:48
Someone ?

**Comment by leobaran-aws** [comment] 2018-06-20 16:51
Sorry to hear you're seeing poor performance in this use case. I will research the root cause, but a possible workaround could be the solution to [this issue](https://github.com/awslabs/aws-codebuild-jenkins-plugin/issues/46), which is to allow users to specify the path of a zip file to upload for the build. This way you could zip the source yourself in a step before the build. This feature is still pending, but I will update this issue when further progress is made.

**Comment by Petezah** [comment] 2018-06-20 18:02
I've seen this also, but didn't realize it was the zip operation that was taking so long.  I've seen this on ECS (EC2 launch type) slaves, and Fargate slaves now.  Also, the operation maxes out the CPU on the Jenkins master at the same time, making all jobs, even ones running on master, take twice as long.  And the job on the slave takes over 30 minutes to start (usually takes 10-20 seconds on master).

@xdexter were you able to workaround the issue by zipping the source yourself?

**Comment by xdexter** [comment] 2018-06-20 18:54
Hi @Petezah 

I got it, my temporary workaround was ran the awscodebuild command on master node (and no in slave). Yes, i did the same test (zip manually on slave container and all works normally).

Regards

**Comment by leobaran-aws** [comment] 2018-06-20 20:57
Until the feature I mentioned is implemented, a workaround could be to zip and upload your source to S3 manually, then use that source to run the build on CodeBuild. Not ideal, but we plan to make this use case easier in the future.

**Comment by Petezah** [comment] 2018-06-26 19:39
I believe the issue is that when a slave is running this step, the Master is trying to zip files that exist on the Slave--ie. the zip file is being built on the Master while files are being read off of the slave.  This is potentially really slow over IPC.  The solution would be to run the whole process on the Slave, and send the whole zip file to the master if necessary.

I'm seeing if I can plumb up a solution, hopefully.

**Comment by Petezah** [comment] 2018-06-26 19:52
No, sorry, I misspoke; the files being zipped are on the Slave--they are streamed over IPC to the Master and zipped, and streamed back over IPC into the zip file, which also exists on the Slave.  So the zipping action occurs on the Master process, but the files all exist on the Slave.  The reason the Zip utility step, mentioned above, is faster is because the whole thing happens inside a MasterToSlave callable.

**Comment by Petezah** [comment] 2018-06-26 21:43
I have tested this PR on a local instance + one of my remote slaves, and it fixes the issue for me.

**Comment by xdexter** [comment] 2018-06-27 16:55
@Petezah It's looks good! @leobaran-aws It's possible merge this PR to master? To be possible i install on my Jenkins?

**Comment by leobaran-aws** [comment] 2018-06-28 16:04
Fixed by 69244e36be3cc363b41c2ba0fb2c45cd840893fc, which will be released in version 0.28 this week.

**Closed by leobaran-aws** 2018-06-28 16:04 UTC

**Comment by xdexter** [comment] 2018-06-28 19:05
Thank you!
