### ISSUE TITLE
Plugin build fails due to tests

### ISSUE THREAD

**Issue by hanks42** [awslabs/aws-codebuild-jenkins-plugin#1] opened 2016-12-02 21:47 UTC
I tried building the plugin as instructed using mvn install and one test failed causing the build to fail

Results :

Failed tests: 
  CodeBuilderPerformTest.testActionConfig:121 null

Tests run: 42, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 57.964s
[INFO] Finished at: Fri Dec 02 15:44:58 CST 2016
[INFO] Final Memory: 32M/860M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.16:test (default-test) on project aws-codebuild: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/jonh/temp/aws-codebuild-jenkins-plugin/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by bcelenza** [comment] 2016-12-03 00:50
Thanks for reporting this!

It looks like this can only be reproduced on certain platforms. Could you let us know what platform (operating system and version) and version of maven you're building with?

**Comment by hanks42** [comment] 2016-12-03 00:59
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty

Apache Maven 3.0.5
Maven home: /usr/share/maven
Java version: 1.7.0_55, vendor: Oracle Corporation
Java home: /usr/java/jdk1.7.0_55/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-101-generic", arch: "amd64", family: "unix"

**Comment by clareliguori** [comment] 2016-12-03 01:08
This is fixed now, one of the unit tests assumed Pacific time zone

**Closed by clareliguori** 2016-12-03 01:08 UTC
