### ISSUE TITLE
Zip files is not released after the job finish

### ISSUE THREAD

**Issue by xdexter** [awslabs/aws-codebuild-jenkins-plugin#55] opened 2018-02-12 18:05 UTC
Hello! 

When i use the AWS Code Build plugin, in the job finish the xxxx.source.zip file is not deleted, i need restart the Jenkins process to file be released, i can see in "lsof" command:

> java      11801    jenkins  572w      REG              202,1    118609     446884 /var/lib/jenkins/jobs/Test/9c179a84-d1ca-4ca5-a9ae-e608b42883c5-source.zip (deleted)

Someone could help me please?

Thank you

**Comment by leobaran-aws** [comment] 2018-02-12 18:10
Thanks for bringing this to our attention, we'll fix the issue as soon as possible.

**Comment by xdexter** [comment] 2018-02-12 18:12
Hi @leobaran-aws Ok, thank you! i'm waiting, if you need somethnig else please contact me.

Thank you!

**Comment by xdexter** [comment] 2018-02-22 17:29
Hello @leobaran-aws,

Do you have some news abou this?

Regards

**Comment by leobaran-aws** [comment] 2018-02-22 21:11
I was not able to reproduce this on my Jenkins instance, but I think I found where the issue may be happening. I've pushed a fix to the branch `zip-file-test`. Can you pull the code, manually build with `mvn install`, upload the new `target/aws-codebuild.hpi`, and see if it fixes the issue?

**Comment by xdexter** [comment] 2018-02-22 23:54
Hello @leobaran-aws 

Perfect, all works now, thank you! Will you merge to master? If yes when you do this can i update plugin in "Jenkins Plugin Manager"?

Regards

**Comment by leobaran-aws** [comment] 2018-02-23 00:00
Great, I'll merge it in. Yes you should be able to update to version 0.19 when we release it.

**Comment by xdexter** [comment] 2018-02-23 00:04
Cool, do you have some estimate date to release?

**Comment by leobaran-aws** [comment] 2018-02-23 15:56
Today, within the next eight hours.

**Comment by xdexter** [comment] 2018-02-23 16:28
Perfect. Thank you.

**Comment by leobaran-aws** [comment] 2018-02-23 19:45
Fixed in 67569674819a304c85a807b0375965601d02e1a8. We'll release this change in version 0.19, which should be available within the next couple of hours.

**Closed by leobaran-aws** 2018-02-23 19:45 UTC

**Comment by xdexter** [comment] 2018-02-23 19:56
Thank you so much @leobaran-aws !
